name: UnicoreConnect
main: uno.unicore.unicoreconnect.bukkit.UnicoreConnectPlugin
version: @app.version@
description: Plugin for integrating UnicoreCMS with the Spigot and Sponge server platforms
authors: [UnicoreProject]
softdepend: [BanManager, LuckPerms, AfkPlus, Vault]
commands:
  money:
    usage: /<command>
    permission: zirconia.money