name: ZirconiaConnect
main: ru.zirconiamc.zirconiaconnect.bukkit.ZirconiaConnect
version: @app.version@
description: ZirconiaConnect
authors: [ZirconiaStudio]
depend: [Vault]
softdepend: [BanManager, LuckPerms]
commands:
  money:
    usage: /<command>
    permission: zirconia.money