name: UnicoreConnect
main: ru.unicorecms.unicoreconnect.bukkit.UnicoreConnectBukkit
version: @app.version@
description: Plugin for integrating UnicoreCMS with the Spigot and Sponge server platforms
authors: [UnicoreProject]
softdepend: [BanManager, LuckPerms, Essentials, Vault, CMI, PlaceholderAPI]




